name: collect

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes (UTC)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: collect-schedule
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run collector (single-shot)
        env:
          GITHUB_ACTIONS: "true"
        run: |
          python collector.py

      - name: Commit & push new data
        run: |
          if [ -n "$(git status --porcelain data/ || true)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git pull --rebase
            git add data/
            git commit -m "data: snapshot $(date -u +'%Y-%m-%dT%H:%MZ')"
            git push
          else
            echo "No data changes."
          fi
